# setup
setup: selflabel

# Threshold
confidence_threshold: 0.95

# EMA
use_ema: False
# ema_alpha: 0.999

# Loss
# Criterion
criterion: confidence-cross-entropy
criterion_kwargs:
   apply_class_balancing: True

# Model
backbone: resnet50
num_heads: 1

# Dataset
train_db_name: imagenetdogs
val_db_name: imagenetdogs
num_classes: 15

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 75
     random: True

transformation_kwargs:
   crop_size: 224
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
# Hyperparameters
epochs: 200
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
batch_size: 256
num_workers: 8

# Scheduler
scheduler: constant 
